print("=" * 40)
print("   DAY 3 REVISION NOTES - LOOPS")
print("   CS50P Lecture 2 + MIT 6.0001 Lecture 2")
date = input("Enter today's date (YYYY-MM-DD): ")
print(f"   Date: {date}")
print("=" * 40 + "\n")
print("KEY RESOURCES WATCHED TODAY: ")
input("1. CS50P Lecture 2: ")
input("2. MIT 6.0001 Lecture 2: ")
input("FOR LOOP → use when: ")
input("WHILE LOOP → use when: ")
input("BREAK   → (in my own words): ")
input("CONTINUE → (in my own words): ")
input("PASS    → (in my own words): ")
input("NESTED LOOP → (in my own words):")
input("BIGGEST INSIGHT FROM CS50P TODAY: ")
input("BIGGEST INSIGHT FROM MIT 6.0001 TODAY: ")
input("SOMETHING I FOUND DIFFICULT: ")
input("SOMETHING I EXPLORED BEYOND THE LESSON: ")