print("=" * 40)
print("PERSONAL INFORMATION CARD")
print("=" * 40)
name = input("Full Name: ")
age = int(input("Age: "))
city = input("City: ")
course = input("Course: ")
goal = input("Career Goal: ")
print("\n" + "=" * 40)
print(f"Name: {name}")
print(f"Age: {age}")
print(f"City: {city}")
print(f"Course: {course}")
print(f"Career Goal: {goal}")
print("=" * 40)
print(f" In 4 years, {name} will be {age + 4} years old")
print(f" and a qualified {course} expert!")
print("=" * 40)
